const items = [
    {
      name: "Chicken Burger",
      price: 300,
      category: "Burger",
      image: '/images/product_01.1.jpg',
    },
    {
        name: "Vegetarian Pizza",
        price: 600,
        category: "Pizza",
        image: '/images/product_2.1.jpg',
      },
      {
        name: "Double Cheese Margherita",
        price: 700,
        category: "Pizza",
        image: '/images/product_3.1.jpg',
      },
      {
        name: "Maxican Green Wave",
        price: 900,
        category: "Pizza",
        image: '/images/product_4.1.jpg',
      },
      {
        name: "Cheese Burger",
        price: 300,
        category: "Burger",
        image: '/images/product_01.3.jpg',
      },
      {
        name: "Royal Cheese Burger",
        price: 200,
        category: "Burger",
        image: '/images/product_04.jpg',
      },
      {
        name: "Seafood Pizza",
        price: 800,
        category: "Pizza",
        image: '/images/product_4.3.png',
      },
      {
        name: "Thin Cheese Pizza",
        price: 900,
        category: "Pizza",
        image: '/images/product_4.2.jpg',
      },
      {
        name: "Pizza With Mushroom",
        price: 800,
        category: "Pizza",
        image: '/images/product_4.1.jpg',
      },
      {
        name: "Classic Hamburger",
        price: 200,
        category: "Burger",
        image: '/images/product_08.jpg',
      },
      {
        name: "7UP.5L",
        price: 70,
        category: "drink",
        image: '/images/product/7UP.5L.png',
      },
      {
        name: "7Up Can",
        price: 120,
        category: "drink",
        image: '/images/product/7Up can.png',
      },
      {
        name: "7UP Reg",
        price: 40,
        category: "drink",
        image: '/images/product/7UP Reg.png',
      },
      {
        name: "7UP",
        price: 40,
        category: "drink",
        image: '/images/product/7UP.5L.png',
      },
      {
        name: "coca-cola 0.5L",
        price: 70,
        category: "drink",
        image: '/images/product/coca-cola 0.5L.png',
      },
      {
        name: "coca-cola Can",
        price: 120,
        category: "drink",
        image: '/images/product/coca-cola Can.png',
      },
      {
        name: "coca-cola Reg",
        price: 120,
        category: "drink",
        image: '/images/product/coca-cola Reg.png',
      },
      {
        name: "coca-cola ",
        price: 120,
        category: "drink",
        image: '/images/product/coca-cola.png',
      },
      {
        name: "Ambur biryani",
        price: 190,
        category: "biryani",
        image: '/images/product/Ambur biryani.png',
      },
      {
        name: "Egg Biryani Recipe.png",
        price: 200,
        category: "biryani",
        image: '/images/product/Egg Biryani Recipe.png',
      },
      {
        name: "Kashmiri Biryani.png",
        price: 180,
        category: "biryani",
        image: '/images/product/Kashmiri Biryani.png',
      },
      {
        name: "Chicken Shawarma Sandwich",
        price: 180,
        category: "shawarma",
        image: '/images/product/Chicken Shawarma Sandwich.png',
      },
      {
        name: "Chicken Shawarma Wraps",
        price: 180,
        category: "shawarma",
        image: '/images/product/Chicken Shawarma Wraps.png',
      },
      {
        name: "Chicken Shawarma",
        price: 210,
        category: "shawarma",
        image: '/images/product/Chicken Shawarma.png',
      },
      {
        name: "Chicken Shawarma",
        price: 180,
        category: "shawarma",
        image: '/images/product/Chicken Shawarma.png',
      },
  ];
  module.exports = items;
  